name: E2E Testes | API & WEB
on: push

jobs:
  pipeline-all-tests-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Instalar dependências
        run: npm install

      - name: Executar testes Cypress
        run: npx cypress run || true  

      - name: Upload de artefatos
        if: always() 
        uses: actions/upload-artifact@v4
        with:
          name: cypress-reports
          path: |
            mochawesome.json
            cypress/reports
